---
openapi: 3.0.3
info:
  title: gl API
  version: 1.0-SNAPSHOT
paths:
  /gl/account:
    get:
      operationId: getAccountList
      parameters:
        - name: filter
          in: query
          schema:
            default: ""
            type: string
        - name: page
          in: query
          schema:
            format: int32
            default: 0
            type: integer
        - name: size
          in: query
          schema:
            format: int32
            default: 20
            type: integer
        - name: sort
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GLAccount'
    post:
      operationId: insertAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GLAccount'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GLAccount'
  /gl/account/{id}:
    get:
      operationId: getAccount
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GLAccount'
    put:
      operationId: updateAccount
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GLAccount'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GLAccount'
    delete:
      operationId: deleteAccount
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "204":
          description: No Content
  /gl/general-ledger:
    get:
      operationId: getGeneralLedgerList
      parameters:
        - name: filter
          in: query
          schema:
            default: ""
            type: string
        - name: page
          in: query
          schema:
            format: int32
            default: 0
            type: integer
        - name: size
          in: query
          schema:
            format: int32
            default: 20
            type: integer
        - name: sort
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GeneralLedger'
    post:
      operationId: insertGeneralLedger
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GeneralLedger'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralLedger'
  /gl/general-ledger/{id}:
    get:
      operationId: getGeneralLedger
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralLedger'
    put:
      operationId: updateTransaction
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GeneralLedger'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralLedger'
    delete:
      operationId: deleteGeneralLedger
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "204":
          description: No Content
  /gl/query:
    post:
      operationId: getQueryResults
      parameters:
        - name: query
          in: query
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: {}
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: {}
  /gl/rest:
    get:
      operationId: getRestList
      parameters:
        - name: filter
          in: query
          schema:
            default: ""
            type: string
        - name: page
          in: query
          schema:
            format: int32
            default: 0
            type: integer
        - name: size
          in: query
          schema:
            format: int32
            default: 20
            type: integer
        - name: sort
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GLRest'
    post:
      operationId: insertRest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GLRest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GLRest'
  /gl/rest/{id}:
    get:
      operationId: getRest
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GLRest'
    put:
      operationId: updateRest
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GLRest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GLRest'
    delete:
      operationId: deleteRest
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "204":
          description: No Content
  /gl/transact:
    post:
      operationId: transact
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GLTransaction'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GLTransaction'
  /gl/transaction:
    get:
      operationId: getTransactionList
      parameters:
        - name: filter
          in: query
          schema:
            default: ""
            type: string
        - name: page
          in: query
          schema:
            format: int32
            default: 0
            type: integer
        - name: size
          in: query
          schema:
            format: int32
            default: 20
            type: integer
        - name: sort
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GLTransaction'
    post:
      operationId: insertTransaction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GLTransaction'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GLTransaction'
  /gl/transaction/{id}:
    get:
      operationId: getTransaction
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GLTransaction'
    put:
      operationId: updateTransaction
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GLTransaction'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GLTransaction'
    delete:
      operationId: deleteTransaction
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "204":
          description: No Content
components:
  schemas:
    GLAccount:
      type: object
      properties:
        id:
          format: int64
          type: integer
        ledger:
          $ref: '#/components/schemas/GeneralLedger'
        number:
          type: string
        partyId:
          format: int64
          type: integer
    GLRest:
      type: object
      properties:
        id:
          format: int64
          type: integer
        amount:
          type: number
        currencyId:
          format: int64
          type: integer
        glAccount:
          $ref: '#/components/schemas/GLAccount'
    GLTransaction:
      type: object
      properties:
        id:
          format: int64
          type: integer
        amount:
          type: number
        credit:
          $ref: '#/components/schemas/GLAccount'
        currencyId:
          format: int64
          type: integer
        date:
          format: date
          type: string
        debit:
          $ref: '#/components/schemas/GLAccount'
    GeneralLedger:
      type: object
      properties:
        id:
          format: int64
          type: integer
        code:
          type: string
        name:
          type: string
