---
openapi: 3.0.3
info:
  title: refs API
  version: 1.0-SNAPSHOT
paths:
  /refs/currency:
    get:
      operationId: getCurrencyList
      parameters:
        - name: filter
          in: query
          schema:
            default: ""
            type: string
        - name: page
          in: query
          schema:
            format: int32
            default: 0
            type: integer
        - name: size
          in: query
          schema:
            format: int32
            default: 20
            type: integer
        - name: sort
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currency'
    post:
      operationId: insertCurrency
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Currency'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Currency'
  /refs/currency/{id}:
    get:
      operationId: getCurrency
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Currency'
    put:
      operationId: updateCurrency
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Currency'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Currency'
    delete:
      operationId: deleteCurrency
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "204":
          description: No Content
  /refs/party:
    get:
      operationId: getPartyList
      parameters:
        - name: filter
          in: query
          schema:
            default: ""
            type: string
        - name: page
          in: query
          schema:
            format: int32
            default: 0
            type: integer
        - name: size
          in: query
          schema:
            format: int32
            default: 20
            type: integer
        - name: sort
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Party'
    post:
      operationId: insertParty
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Party'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Party'
  /refs/party/{id}:
    get:
      operationId: getParty
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Party'
    put:
      operationId: updateParty
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Party'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Party'
    delete:
      operationId: deleteParty
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "204":
          description: No Content
  /refs/query:
    post:
      operationId: getQueryResults
      parameters:
        - name: query
          in: query
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: {}
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: {}
components:
  schemas:
    Currency:
      type: object
      properties:
        id:
          format: int64
          type: integer
        code:
          type: string
    Party:
      type: object
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
